### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by jopio0819alt** [Cosmeak/PteroBot#4]
When i try to acces my server using this system, it prints;
[ERROR] AxiosError: Request failed with status code 404
[ERROR] AxiosError: Request failed with status code 404

**Comment by Cosmeak** [comment]
Hi, can you share more information about your system please.

The first thing that comes to mind would be a variable in the .env that is missing or not in the right format. Check the `PTERO_HOST`, it shouldn't end with a slash, it's an error in my documentation, i will update it soon.

**Comment by jopio0819alt** [comment]
Thanks. That was the issue.
